-- Atualização do catálogo de serviços para o catálogo 2026 (ata e catálogo de 01/10/2026).
--
-- Fonte: src/lib/inicializar.ts (SERVICOS_DO_CATALOGO). Preços: Grande São Paulo.
-- Idempotente: serviço que já existe (pelo nome novo OU por um nome anterior) é
-- ATUALIZADO no lugar — o id e os pedidos que apontam para ele continuam
-- valendo —, e o que não existe é criado. Nada é apagado: o que saiu do
-- catálogo é desativado.
--
-- Rodar UMA vez, depois que a migration 20261001180000 estiver aplicada.
BEGIN;

-- AirFlow GBT Machine · AirFlow – GBT Machine (1 paciente)
UPDATE "Servico" SET "nome" = 'AirFlow – GBT Machine (1 paciente)', "familia" = 'AirFlow GBT Machine', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Tratamento por paciente (Guided Biofilm Therapy): locação do GBT Machine com 1 cirurgião dentista treinado na metodologia GBT. Insumos inclusos: pó de eritritol, revelador de biofilme, ponta Perioflow descartável e ponta ultrassônica PS.', "duracaoMin" = 60, "valorPadraoCentavos" = 50000, "exigeEquipamento" = true, "tipoEquipamento" = 'GBT AirFlow', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('AirFlow – GBT Machine (1 paciente)', 'GBT Machine – AirFlow') ORDER BY ("nome" = 'AirFlow – GBT Machine (1 paciente)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'AirFlow – GBT Machine (1 paciente)', 'AirFlow GBT Machine', 'ODONTOLOGIA'::"CategoriaServico", 'Tratamento por paciente (Guided Biofilm Therapy): locação do GBT Machine com 1 cirurgião dentista treinado na metodologia GBT. Insumos inclusos: pó de eritritol, revelador de biofilme, ponta Perioflow descartável e ponta ultrassônica PS.', 60, 50000, true, 'GBT AirFlow', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('AirFlow – GBT Machine (1 paciente)', 'GBT Machine – AirFlow'));

-- AirFlow GBT Machine · AirFlow – GBT Machine (pacote 3 pacientes)
UPDATE "Servico" SET "nome" = 'AirFlow – GBT Machine (pacote 3 pacientes)', "familia" = 'AirFlow GBT Machine', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Locação do GBT Machine por 4 horas para 3 pacientes, com 1 cirurgião dentista (primeiro paciente), insumos e 1 câmara de pó AirFlow Plus.', "duracaoMin" = 240, "valorPadraoCentavos" = 120000, "exigeEquipamento" = true, "tipoEquipamento" = 'GBT AirFlow', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('AirFlow – GBT Machine (pacote 3 pacientes)') ORDER BY ("nome" = 'AirFlow – GBT Machine (pacote 3 pacientes)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'AirFlow – GBT Machine (pacote 3 pacientes)', 'AirFlow GBT Machine', 'ODONTOLOGIA'::"CategoriaServico", 'Locação do GBT Machine por 4 horas para 3 pacientes, com 1 cirurgião dentista (primeiro paciente), insumos e 1 câmara de pó AirFlow Plus.', 240, 120000, true, 'GBT AirFlow', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('AirFlow – GBT Machine (pacote 3 pacientes)'));

-- AirFlow GBT Machine · AirFlow – GBT Machine (pacote 6 pacientes)
UPDATE "Servico" SET "nome" = 'AirFlow – GBT Machine (pacote 6 pacientes)', "familia" = 'AirFlow GBT Machine', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Locação do GBT Machine por 6 horas para 6 pacientes, com 1 cirurgião dentista (primeiro paciente), insumos e 2 câmaras de pó AirFlow Plus.', "duracaoMin" = 360, "valorPadraoCentavos" = 210000, "exigeEquipamento" = true, "tipoEquipamento" = 'GBT AirFlow', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('AirFlow – GBT Machine (pacote 6 pacientes)') ORDER BY ("nome" = 'AirFlow – GBT Machine (pacote 6 pacientes)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'AirFlow – GBT Machine (pacote 6 pacientes)', 'AirFlow GBT Machine', 'ODONTOLOGIA'::"CategoriaServico", 'Locação do GBT Machine por 6 horas para 6 pacientes, com 1 cirurgião dentista (primeiro paciente), insumos e 2 câmaras de pó AirFlow Plus.', 360, 210000, true, 'GBT AirFlow', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('AirFlow – GBT Machine (pacote 6 pacientes)'));

-- AirFlow GBT Machine · AirFlow – GBT Machine (pacote 9 pacientes)
UPDATE "Servico" SET "nome" = 'AirFlow – GBT Machine (pacote 9 pacientes)', "familia" = 'AirFlow GBT Machine', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Locação do GBT Machine por 8 horas para 9 pacientes, com 1 cirurgião dentista (primeiro paciente), insumos e 3 câmaras de pó AirFlow Plus.', "duracaoMin" = 480, "valorPadraoCentavos" = 300000, "exigeEquipamento" = true, "tipoEquipamento" = 'GBT AirFlow', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('AirFlow – GBT Machine (pacote 9 pacientes)') ORDER BY ("nome" = 'AirFlow – GBT Machine (pacote 9 pacientes)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'AirFlow – GBT Machine (pacote 9 pacientes)', 'AirFlow GBT Machine', 'ODONTOLOGIA'::"CategoriaServico", 'Locação do GBT Machine por 8 horas para 9 pacientes, com 1 cirurgião dentista (primeiro paciente), insumos e 3 câmaras de pó AirFlow Plus.', 480, 300000, true, 'GBT AirFlow', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('AirFlow – GBT Machine (pacote 9 pacientes)'));

-- LiteTouch™ · LiteTouch – Remoção de Lentes, Facetas e Coroas
UPDATE "Servico" SET "nome" = 'LiteTouch – Remoção de Lentes, Facetas e Coroas', "familia" = 'LiteTouch™', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Por paciente, até 2 elementos; cada elemento adicional soma R$ 400,00. Realizado por cirurgião dentista especialista Hemoderi + assistente.', "duracaoMin" = 60, "valorPadraoCentavos" = 75000, "exigeEquipamento" = true, "tipoEquipamento" = 'Laser LiteTouch', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = true, "rotuloQuantidade" = 'elementos', "quantidadeMinima" = 1, "quantidadeIncluida" = 2, "valorAdicionalCentavos" = 40000, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('LiteTouch – Remoção de Lentes, Facetas e Coroas', 'LiteTouch – Laser de Alta Potência') ORDER BY ("nome" = 'LiteTouch – Remoção de Lentes, Facetas e Coroas') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'LiteTouch – Remoção de Lentes, Facetas e Coroas', 'LiteTouch™', 'ODONTOLOGIA'::"CategoriaServico", 'Por paciente, até 2 elementos; cada elemento adicional soma R$ 400,00. Realizado por cirurgião dentista especialista Hemoderi + assistente.', 60, 75000, true, 'Laser LiteTouch', 'PACIENTE'::"UnidadeCobranca", true, 'elementos', 1, 2, 40000, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('LiteTouch – Remoção de Lentes, Facetas e Coroas', 'LiteTouch – Laser de Alta Potência'));

-- LiteTouch™ · LiteTouch – Remoção de Lentes, Facetas e Coroas (FULL)
UPDATE "Servico" SET "nome" = 'LiteTouch – Remoção de Lentes, Facetas e Coroas (FULL)', "familia" = 'LiteTouch™', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Por paciente, remoção acima de 5 elementos. Realizado por cirurgião dentista especialista Hemoderi + assistente; levamos todos os instrumentais.', "duracaoMin" = 120, "valorPadraoCentavos" = 150000, "exigeEquipamento" = true, "tipoEquipamento" = 'Laser LiteTouch', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('LiteTouch – Remoção de Lentes, Facetas e Coroas (FULL)') ORDER BY ("nome" = 'LiteTouch – Remoção de Lentes, Facetas e Coroas (FULL)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'LiteTouch – Remoção de Lentes, Facetas e Coroas (FULL)', 'LiteTouch™', 'ODONTOLOGIA'::"CategoriaServico", 'Por paciente, remoção acima de 5 elementos. Realizado por cirurgião dentista especialista Hemoderi + assistente; levamos todos os instrumentais.', 120, 150000, true, 'Laser LiteTouch', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('LiteTouch – Remoção de Lentes, Facetas e Coroas (FULL)'));

-- LiteTouch™ · LiteTouch – Dessensibilização Dentária
UPDATE "Servico" SET "nome" = 'LiteTouch – Dessensibilização Dentária', "familia" = 'LiteTouch™', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Por paciente, sem limite de elementos. Cirurgião dentista especialista Hemoderi + assistente; insumos e EPIs necessários inclusos.', "duracaoMin" = 45, "valorPadraoCentavos" = 75000, "exigeEquipamento" = true, "tipoEquipamento" = 'Laser LiteTouch', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('LiteTouch – Dessensibilização Dentária') ORDER BY ("nome" = 'LiteTouch – Dessensibilização Dentária') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'LiteTouch – Dessensibilização Dentária', 'LiteTouch™', 'ODONTOLOGIA'::"CategoriaServico", 'Por paciente, sem limite de elementos. Cirurgião dentista especialista Hemoderi + assistente; insumos e EPIs necessários inclusos.', 45, 75000, true, 'Laser LiteTouch', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('LiteTouch – Dessensibilização Dentária'));

-- LiteTouch™ · LiteTouch – Frenectomia
UPDATE "Servico" SET "nome" = 'LiteTouch – Frenectomia', "familia" = 'LiteTouch™', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Por paciente. Cirurgião dentista especialista Hemoderi + assistente; instrumentais, insumos e EPIs necessários inclusos.', "duracaoMin" = 60, "valorPadraoCentavos" = 150000, "exigeEquipamento" = true, "tipoEquipamento" = 'Laser LiteTouch', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('LiteTouch – Frenectomia') ORDER BY ("nome" = 'LiteTouch – Frenectomia') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'LiteTouch – Frenectomia', 'LiteTouch™', 'ODONTOLOGIA'::"CategoriaServico", 'Por paciente. Cirurgião dentista especialista Hemoderi + assistente; instrumentais, insumos e EPIs necessários inclusos.', 60, 150000, true, 'Laser LiteTouch', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('LiteTouch – Frenectomia'));

-- Rotamix Sedação Consciente · Sedação Consciente – Grande São Paulo
UPDATE "Servico" SET "nome" = 'Sedação Consciente – Grande São Paulo', "familia" = 'Rotamix Sedação Consciente', "categoria" = 'SAUDE'::"CategoriaServico", "descricao" = 'Valor por cirurgia/paciente, até 3 horas de funcionamento do equipamento. Cirurgião dentista habilitado disponível durante todo o procedimento, cilindros de oxigênio e óxido nitroso medicinal e monitoramento dos sinais vitais. Atendimentos dentro da Grande São Paulo.', "duracaoMin" = 180, "valorPadraoCentavos" = 85000, "exigeEquipamento" = false, "tipoEquipamento" = NULL, "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Sedação Consciente – Grande São Paulo', 'Sedação Consciente') ORDER BY ("nome" = 'Sedação Consciente – Grande São Paulo') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Sedação Consciente – Grande São Paulo', 'Rotamix Sedação Consciente', 'SAUDE'::"CategoriaServico", 'Valor por cirurgia/paciente, até 3 horas de funcionamento do equipamento. Cirurgião dentista habilitado disponível durante todo o procedimento, cilindros de oxigênio e óxido nitroso medicinal e monitoramento dos sinais vitais. Atendimentos dentro da Grande São Paulo.', 180, 85000, false, NULL, 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Sedação Consciente – Grande São Paulo', 'Sedação Consciente'));

-- Rotamix Sedação Consciente · Sedação Consciente – Interior (até 150 km)
UPDATE "Servico" SET "nome" = 'Sedação Consciente – Interior (até 150 km)', "familia" = 'Rotamix Sedação Consciente', "categoria" = 'SAUDE'::"CategoriaServico", "descricao" = 'Mesmo serviço, para atendimentos fora da Grande São Paulo até 150 km. Acima de 150 km da cidade de São Paulo, consulte o deslocamento.', "duracaoMin" = 180, "valorPadraoCentavos" = 105000, "exigeEquipamento" = false, "tipoEquipamento" = NULL, "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Sedação Consciente – Interior (até 150 km)') ORDER BY ("nome" = 'Sedação Consciente – Interior (até 150 km)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Sedação Consciente – Interior (até 150 km)', 'Rotamix Sedação Consciente', 'SAUDE'::"CategoriaServico", 'Mesmo serviço, para atendimentos fora da Grande São Paulo até 150 km. Acima de 150 km da cidade de São Paulo, consulte o deslocamento.', 180, 105000, false, NULL, 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Sedação Consciente – Interior (até 150 km)'));

-- Piezosurgery Mectron Touch · Piezosurgery Mectron Touch
UPDATE "Servico" SET "nome" = 'Piezosurgery Mectron Touch', "familia" = 'Piezosurgery Mectron Touch', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Locação para 1 cirurgia/paciente, com pontas inclusas e profissional para instrumentação cirúrgica do equipamento.', "duracaoMin" = 60, "valorPadraoCentavos" = 63500, "exigeEquipamento" = true, "tipoEquipamento" = 'Piezosurgery Mectron Touch', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Piezosurgery Mectron Touch') ORDER BY ("nome" = 'Piezosurgery Mectron Touch') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Piezosurgery Mectron Touch', 'Piezosurgery Mectron Touch', 'ODONTOLOGIA'::"CategoriaServico", 'Locação para 1 cirurgia/paciente, com pontas inclusas e profissional para instrumentação cirúrgica do equipamento.', 60, 63500, true, 'Piezosurgery Mectron Touch', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Piezosurgery Mectron Touch'));

-- Piezosurgery Mectron Touch · Piezosurgery + Stickybone + Membranas
UPDATE "Servico" SET "nome" = 'Piezosurgery + Stickybone + Membranas', "familia" = 'Piezosurgery Mectron Touch', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Pacote promocional: produção de membranas e Stickybone, profissional para instrumentação cirúrgica e locação do Piezosurgery Mectron para 1 cirurgia/paciente.', "duracaoMin" = 90, "valorPadraoCentavos" = 93500, "exigeEquipamento" = true, "tipoEquipamento" = 'Piezosurgery Mectron Touch', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Piezosurgery + Stickybone + Membranas') ORDER BY ("nome" = 'Piezosurgery + Stickybone + Membranas') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Piezosurgery + Stickybone + Membranas', 'Piezosurgery Mectron Touch', 'ODONTOLOGIA'::"CategoriaServico", 'Pacote promocional: produção de membranas e Stickybone, profissional para instrumentação cirúrgica e locação do Piezosurgery Mectron para 1 cirurgia/paciente.', 90, 93500, true, 'Piezosurgery Mectron Touch', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Piezosurgery + Stickybone + Membranas'));

-- Cobertura Fotográfica · Cobertura Fotográfica Odontológica
UPDATE "Servico" SET "nome" = 'Cobertura Fotográfica Odontológica', "familia" = 'Cobertura Fotográfica', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Profissional especialista em fotografia odontológica intra oral, disponível por 4 horas. Fotos tratadas em Photoshop e arquivo total das fotos produzidas; EPIs, iluminação, máquina fotográfica profissional e materiais estéreis inclusos. Adicional de deslocamento para cidades fora das regiões metropolitanas.', "duracaoMin" = 240, "valorPadraoCentavos" = 67000, "exigeEquipamento" = false, "tipoEquipamento" = NULL, "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Cobertura Fotográfica Odontológica') ORDER BY ("nome" = 'Cobertura Fotográfica Odontológica') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Cobertura Fotográfica Odontológica', 'Cobertura Fotográfica', 'ODONTOLOGIA'::"CategoriaServico", 'Profissional especialista em fotografia odontológica intra oral, disponível por 4 horas. Fotos tratadas em Photoshop e arquivo total das fotos produzidas; EPIs, iluminação, máquina fotográfica profissional e materiais estéreis inclusos. Adicional de deslocamento para cidades fora das regiões metropolitanas.', 240, 67000, false, NULL, 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Cobertura Fotográfica Odontológica'));

-- Ultrassom Micro Focado · Ultrassom Atria® – Tratamento Facial
UPDATE "Servico" SET "nome" = 'Ultrassom Atria® – Tratamento Facial', "familia" = 'Ultrassom Micro Focado', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Por paciente, mínimo de 400 disparos (R$ 2,47 o disparo) = R$ 990,00; acima de 400, R$ 1,70 por disparo adicional. Acompanhado por biomédico esteta especialista Hemoderi.', "duracaoMin" = 60, "valorPadraoCentavos" = 99000, "exigeEquipamento" = true, "tipoEquipamento" = 'Atria Ultrassom', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = true, "rotuloQuantidade" = 'disparos', "quantidadeMinima" = 400, "quantidadeIncluida" = 400, "valorAdicionalCentavos" = 170, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Tratamento Facial', 'Ultrassom Micro e Macrofocado – Atria®') ORDER BY ("nome" = 'Ultrassom Atria® – Tratamento Facial') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Ultrassom Atria® – Tratamento Facial', 'Ultrassom Micro Focado', 'ESTETICA'::"CategoriaServico", 'Por paciente, mínimo de 400 disparos (R$ 2,47 o disparo) = R$ 990,00; acima de 400, R$ 1,70 por disparo adicional. Acompanhado por biomédico esteta especialista Hemoderi.', 60, 99000, true, 'Atria Ultrassom', 'PACIENTE'::"UnidadeCobranca", true, 'disparos', 400, 400, 170, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Tratamento Facial', 'Ultrassom Micro e Macrofocado – Atria®'));

-- Ultrassom Micro Focado · Ultrassom Atria® – Tratamento Corporal
UPDATE "Servico" SET "nome" = 'Ultrassom Atria® – Tratamento Corporal', "familia" = 'Ultrassom Micro Focado', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Por paciente, mínimo de 900 disparos (R$ 2,00 o disparo) = R$ 1.800,00; acima de 900, R$ 1,70 por disparo adicional. Acompanhado por biomédico esteta especialista Hemoderi.', "duracaoMin" = 90, "valorPadraoCentavos" = 180000, "exigeEquipamento" = true, "tipoEquipamento" = 'Atria Ultrassom', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = true, "rotuloQuantidade" = 'disparos', "quantidadeMinima" = 900, "quantidadeIncluida" = 900, "valorAdicionalCentavos" = 170, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Tratamento Corporal') ORDER BY ("nome" = 'Ultrassom Atria® – Tratamento Corporal') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Ultrassom Atria® – Tratamento Corporal', 'Ultrassom Micro Focado', 'ESTETICA'::"CategoriaServico", 'Por paciente, mínimo de 900 disparos (R$ 2,00 o disparo) = R$ 1.800,00; acima de 900, R$ 1,70 por disparo adicional. Acompanhado por biomédico esteta especialista Hemoderi.', 90, 180000, true, 'Atria Ultrassom', 'PACIENTE'::"UnidadeCobranca", true, 'disparos', 900, 900, 170, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Tratamento Corporal'));

-- Ultrassom Micro Focado · Ultrassom Atria® – Facial 900 disparos (4 h)
UPDATE "Servico" SET "nome" = 'Ultrassom Atria® – Facial 900 disparos (4 h)', "familia" = 'Ultrassom Micro Focado', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Locação do equipamento por período de 4 horas, mínimo de 900 disparos a R$ 2,00. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', "duracaoMin" = 240, "valorPadraoCentavos" = 180000, "exigeEquipamento" = true, "tipoEquipamento" = 'Atria Ultrassom', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = true, "rotuloQuantidade" = 'disparos', "quantidadeMinima" = 900, "quantidadeIncluida" = 900, "valorAdicionalCentavos" = 170, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 900 disparos (4 h)') ORDER BY ("nome" = 'Ultrassom Atria® – Facial 900 disparos (4 h)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Ultrassom Atria® – Facial 900 disparos (4 h)', 'Ultrassom Micro Focado', 'ESTETICA'::"CategoriaServico", 'Locação do equipamento por período de 4 horas, mínimo de 900 disparos a R$ 2,00. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', 240, 180000, true, 'Atria Ultrassom', 'PERIODO'::"UnidadeCobranca", true, 'disparos', 900, 900, 170, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 900 disparos (4 h)'));

-- Ultrassom Micro Focado · Ultrassom Atria® – Facial 1600 disparos (8 h)
UPDATE "Servico" SET "nome" = 'Ultrassom Atria® – Facial 1600 disparos (8 h)', "familia" = 'Ultrassom Micro Focado', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Locação do equipamento por período de 8 horas, mínimo de 1600 disparos a R$ 2,00. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', "duracaoMin" = 480, "valorPadraoCentavos" = 320000, "exigeEquipamento" = true, "tipoEquipamento" = 'Atria Ultrassom', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = true, "rotuloQuantidade" = 'disparos', "quantidadeMinima" = 1600, "quantidadeIncluida" = 1600, "valorAdicionalCentavos" = 170, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 1600 disparos (8 h)') ORDER BY ("nome" = 'Ultrassom Atria® – Facial 1600 disparos (8 h)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Ultrassom Atria® – Facial 1600 disparos (8 h)', 'Ultrassom Micro Focado', 'ESTETICA'::"CategoriaServico", 'Locação do equipamento por período de 8 horas, mínimo de 1600 disparos a R$ 2,00. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', 480, 320000, true, 'Atria Ultrassom', 'PERIODO'::"UnidadeCobranca", true, 'disparos', 1600, 1600, 170, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 1600 disparos (8 h)'));

-- Ultrassom Micro Focado · Ultrassom Atria® – Facial 3000 disparos (8 h)
UPDATE "Servico" SET "nome" = 'Ultrassom Atria® – Facial 3000 disparos (8 h)', "familia" = 'Ultrassom Micro Focado', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Locação do equipamento por período de 8 horas, a partir de 3000 disparos a R$ 1,86. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', "duracaoMin" = 480, "valorPadraoCentavos" = 558000, "exigeEquipamento" = true, "tipoEquipamento" = 'Atria Ultrassom', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = true, "rotuloQuantidade" = 'disparos', "quantidadeMinima" = 3000, "quantidadeIncluida" = 3000, "valorAdicionalCentavos" = 170, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 3000 disparos (8 h)') ORDER BY ("nome" = 'Ultrassom Atria® – Facial 3000 disparos (8 h)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Ultrassom Atria® – Facial 3000 disparos (8 h)', 'Ultrassom Micro Focado', 'ESTETICA'::"CategoriaServico", 'Locação do equipamento por período de 8 horas, a partir de 3000 disparos a R$ 1,86. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', 480, 558000, true, 'Atria Ultrassom', 'PERIODO'::"UnidadeCobranca", true, 'disparos', 3000, 3000, 170, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 3000 disparos (8 h)'));

-- Ultrassom Micro Focado · Ultrassom Atria® – Facial 5000 disparos (12 h)
UPDATE "Servico" SET "nome" = 'Ultrassom Atria® – Facial 5000 disparos (12 h)', "familia" = 'Ultrassom Micro Focado', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Locação do equipamento por período de 12 horas, a partir de 5000 disparos a R$ 1,79. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', "duracaoMin" = 720, "valorPadraoCentavos" = 895000, "exigeEquipamento" = true, "tipoEquipamento" = 'Atria Ultrassom', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = true, "rotuloQuantidade" = 'disparos', "quantidadeMinima" = 5000, "quantidadeIncluida" = 5000, "valorAdicionalCentavos" = 170, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 5000 disparos (12 h)') ORDER BY ("nome" = 'Ultrassom Atria® – Facial 5000 disparos (12 h)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Ultrassom Atria® – Facial 5000 disparos (12 h)', 'Ultrassom Micro Focado', 'ESTETICA'::"CategoriaServico", 'Locação do equipamento por período de 12 horas, a partir de 5000 disparos a R$ 1,79. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', 720, 895000, true, 'Atria Ultrassom', 'PERIODO'::"UnidadeCobranca", true, 'disparos', 5000, 5000, 170, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 5000 disparos (12 h)'));

-- Ultrassom Micro Focado · Ultrassom Atria® – Facial 7000 disparos (12 h)
UPDATE "Servico" SET "nome" = 'Ultrassom Atria® – Facial 7000 disparos (12 h)', "familia" = 'Ultrassom Micro Focado', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Locação do equipamento por período de 12 horas, a partir de 7000 disparos a R$ 1,70. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', "duracaoMin" = 720, "valorPadraoCentavos" = 1190000, "exigeEquipamento" = true, "tipoEquipamento" = 'Atria Ultrassom', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = true, "rotuloQuantidade" = 'disparos', "quantidadeMinima" = 7000, "quantidadeIncluida" = 7000, "valorAdicionalCentavos" = 170, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 7000 disparos (12 h)') ORDER BY ("nome" = 'Ultrassom Atria® – Facial 7000 disparos (12 h)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Ultrassom Atria® – Facial 7000 disparos (12 h)', 'Ultrassom Micro Focado', 'ESTETICA'::"CategoriaServico", 'Locação do equipamento por período de 12 horas, a partir de 7000 disparos a R$ 1,70. Disparo adicional R$ 1,70. Acompanhado por biomédico esteta especialista Hemoderi.', 720, 1190000, true, 'Atria Ultrassom', 'PERIODO'::"UnidadeCobranca", true, 'disparos', 7000, 7000, 170, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Ultrassom Atria® – Facial 7000 disparos (12 h)'));

-- Megaderme – Radiofrequência Microagulhada · Megaderme – Tratamento por paciente
UPDATE "Servico" SET "nome" = 'Megaderme – Tratamento por paciente', "familia" = 'Megaderme – Radiofrequência Microagulhada', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Locação do Megaderme com ponteira Eletroderme RF. Inclui 1 spot com 40 agulhas (o mesmo spot faz corporal e facial na mesma sessão). Acompanhado por biomédico esteta especialista Hemoderi.', "duracaoMin" = 60, "valorPadraoCentavos" = 78000, "exigeEquipamento" = true, "tipoEquipamento" = 'Megaderme', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Megaderme – Tratamento por paciente', 'Megaderme® – Radiofrequência Microagulhada') ORDER BY ("nome" = 'Megaderme – Tratamento por paciente') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Megaderme – Tratamento por paciente', 'Megaderme – Radiofrequência Microagulhada', 'ESTETICA'::"CategoriaServico", 'Locação do Megaderme com ponteira Eletroderme RF. Inclui 1 spot com 40 agulhas (o mesmo spot faz corporal e facial na mesma sessão). Acompanhado por biomédico esteta especialista Hemoderi.', 60, 78000, true, 'Megaderme', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Megaderme – Tratamento por paciente', 'Megaderme® – Radiofrequência Microagulhada'));

-- Megaderme – Radiofrequência Microagulhada · Megaderme – Pacote 2 Pacientes
UPDATE "Servico" SET "nome" = 'Megaderme – Pacote 2 Pacientes', "familia" = 'Megaderme – Radiofrequência Microagulhada', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Locação do Megaderme por 2 horas, 1 spot com 40 agulhas por paciente — R$ 700,00 por paciente.', "duracaoMin" = 120, "valorPadraoCentavos" = 140000, "exigeEquipamento" = true, "tipoEquipamento" = 'Megaderme', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Megaderme – Pacote 2 Pacientes') ORDER BY ("nome" = 'Megaderme – Pacote 2 Pacientes') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Megaderme – Pacote 2 Pacientes', 'Megaderme – Radiofrequência Microagulhada', 'ESTETICA'::"CategoriaServico", 'Locação do Megaderme por 2 horas, 1 spot com 40 agulhas por paciente — R$ 700,00 por paciente.', 120, 140000, true, 'Megaderme', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Megaderme – Pacote 2 Pacientes'));

-- Megaderme – Radiofrequência Microagulhada · Megaderme – Pacote 3 Pacientes
UPDATE "Servico" SET "nome" = 'Megaderme – Pacote 3 Pacientes', "familia" = 'Megaderme – Radiofrequência Microagulhada', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Locação do Megaderme por 3 horas, 1 spot com 40 agulhas por paciente — R$ 670,00 por paciente.', "duracaoMin" = 180, "valorPadraoCentavos" = 200000, "exigeEquipamento" = true, "tipoEquipamento" = 'Megaderme', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Megaderme – Pacote 3 Pacientes') ORDER BY ("nome" = 'Megaderme – Pacote 3 Pacientes') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Megaderme – Pacote 3 Pacientes', 'Megaderme – Radiofrequência Microagulhada', 'ESTETICA'::"CategoriaServico", 'Locação do Megaderme por 3 horas, 1 spot com 40 agulhas por paciente — R$ 670,00 por paciente.', 180, 200000, true, 'Megaderme', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Megaderme – Pacote 3 Pacientes'));

-- Megaderme – Radiofrequência Microagulhada · Megaderme – Pacote 4 Pacientes
UPDATE "Servico" SET "nome" = 'Megaderme – Pacote 4 Pacientes', "familia" = 'Megaderme – Radiofrequência Microagulhada', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Locação do Megaderme por 4 horas, 1 spot com 40 agulhas por paciente — R$ 650,00 por paciente.', "duracaoMin" = 240, "valorPadraoCentavos" = 260000, "exigeEquipamento" = true, "tipoEquipamento" = 'Megaderme', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Megaderme – Pacote 4 Pacientes') ORDER BY ("nome" = 'Megaderme – Pacote 4 Pacientes') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Megaderme – Pacote 4 Pacientes', 'Megaderme – Radiofrequência Microagulhada', 'ESTETICA'::"CategoriaServico", 'Locação do Megaderme por 4 horas, 1 spot com 40 agulhas por paciente — R$ 650,00 por paciente.', 240, 260000, true, 'Megaderme', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Megaderme – Pacote 4 Pacientes'));

-- Platinum Platform · Platinum Platform – Pacote 1 Paciente
UPDATE "Servico" SET "nome" = 'Platinum Platform – Pacote 1 Paciente', "familia" = 'Platinum Platform', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Valor por paciente: locação da Platinum Platform com ponteiras IPL, Er:Yag e Q-Switched, acompanhada por biomédico esteta especialista Hemoderi.', "duracaoMin" = 60, "valorPadraoCentavos" = 99000, "exigeEquipamento" = true, "tipoEquipamento" = 'Platinum Platform', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Platinum Platform – Pacote 1 Paciente', 'Platinum Platform') ORDER BY ("nome" = 'Platinum Platform – Pacote 1 Paciente') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Platinum Platform – Pacote 1 Paciente', 'Platinum Platform', 'ESTETICA'::"CategoriaServico", 'Valor por paciente: locação da Platinum Platform com ponteiras IPL, Er:Yag e Q-Switched, acompanhada por biomédico esteta especialista Hemoderi.', 60, 99000, true, 'Platinum Platform', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Platinum Platform – Pacote 1 Paciente', 'Platinum Platform'));

-- Platinum Platform · Platinum Platform – Locação 4 Horas
UPDATE "Servico" SET "nome" = 'Platinum Platform – Locação 4 Horas', "familia" = 'Platinum Platform', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Valor por período, sem limite de pacientes: locação da Platinum Platform por 4 horas, com ponteiras IPL, Er:Yag e Q-Switched e biomédico esteta especialista Hemoderi.', "duracaoMin" = 240, "valorPadraoCentavos" = 150000, "exigeEquipamento" = true, "tipoEquipamento" = 'Platinum Platform', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Platinum Platform – Locação 4 Horas') ORDER BY ("nome" = 'Platinum Platform – Locação 4 Horas') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Platinum Platform – Locação 4 Horas', 'Platinum Platform', 'ESTETICA'::"CategoriaServico", 'Valor por período, sem limite de pacientes: locação da Platinum Platform por 4 horas, com ponteiras IPL, Er:Yag e Q-Switched e biomédico esteta especialista Hemoderi.', 240, 150000, true, 'Platinum Platform', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Platinum Platform – Locação 4 Horas'));

-- Platinum Platform · Platinum Platform – Locação 8 Horas
UPDATE "Servico" SET "nome" = 'Platinum Platform – Locação 8 Horas', "familia" = 'Platinum Platform', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Valor por período, sem limite de pacientes: locação da Platinum Platform por 8 horas, com ponteiras IPL, Er:Yag e Q-Switched e biomédico esteta especialista Hemoderi.', "duracaoMin" = 480, "valorPadraoCentavos" = 199000, "exigeEquipamento" = true, "tipoEquipamento" = 'Platinum Platform', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Platinum Platform – Locação 8 Horas') ORDER BY ("nome" = 'Platinum Platform – Locação 8 Horas') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Platinum Platform – Locação 8 Horas', 'Platinum Platform', 'ESTETICA'::"CategoriaServico", 'Valor por período, sem limite de pacientes: locação da Platinum Platform por 8 horas, com ponteiras IPL, Er:Yag e Q-Switched e biomédico esteta especialista Hemoderi.', 480, 199000, true, 'Platinum Platform', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Platinum Platform – Locação 8 Horas'));

-- Laser Therapy EC · Laser Therapy EC + ILIB
UPDATE "Servico" SET "nome" = 'Laser Therapy EC + ILIB', "familia" = 'Laser Therapy EC', "categoria" = 'SAUDE'::"CategoriaServico", "descricao" = 'Valor por paciente. Procedimento acompanhado por profissional com as orientações de uso do equipamento; acompanha ILIB.', "duracaoMin" = 60, "valorPadraoCentavos" = 30000, "exigeEquipamento" = true, "tipoEquipamento" = 'Laser Therapy EC + ILIB', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Laser Therapy EC + ILIB') ORDER BY ("nome" = 'Laser Therapy EC + ILIB') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Laser Therapy EC + ILIB', 'Laser Therapy EC', 'SAUDE'::"CategoriaServico", 'Valor por paciente. Procedimento acompanhado por profissional com as orientações de uso do equipamento; acompanha ILIB.', 60, 30000, true, 'Laser Therapy EC + ILIB', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Laser Therapy EC + ILIB'));

-- Laser Therapy EC · Laser Therapy EC + ILIB (adicional a outro serviço)
UPDATE "Servico" SET "nome" = 'Laser Therapy EC + ILIB (adicional a outro serviço)', "familia" = 'Laser Therapy EC', "categoria" = 'SAUDE'::"CategoriaServico", "descricao" = 'Valor exclusivo para contratação junto com outro serviço Hemoderi no mesmo atendimento; acompanha ILIB.', "duracaoMin" = 30, "valorPadraoCentavos" = 10000, "exigeEquipamento" = true, "tipoEquipamento" = 'Laser Therapy EC + ILIB', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Laser Therapy EC + ILIB (adicional a outro serviço)') ORDER BY ("nome" = 'Laser Therapy EC + ILIB (adicional a outro serviço)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Laser Therapy EC + ILIB (adicional a outro serviço)', 'Laser Therapy EC', 'SAUDE'::"CategoriaServico", 'Valor exclusivo para contratação junto com outro serviço Hemoderi no mesmo atendimento; acompanha ILIB.', 30, 10000, true, 'Laser Therapy EC + ILIB', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Laser Therapy EC + ILIB (adicional a outro serviço)'));

-- Bisturi Elétrico · Bisturi Elétrico – Por Cirurgia
UPDATE "Servico" SET "nome" = 'Bisturi Elétrico – Por Cirurgia', "familia" = 'Bisturi Elétrico', "categoria" = 'SAUDE'::"CategoriaServico", "descricao" = 'Valor por cirurgia. Profissional Hemoderi entrega, testa e acompanha a cirurgia; inclusas as pontas do kit odontológico da EMAI.', "duracaoMin" = 60, "valorPadraoCentavos" = 50000, "exigeEquipamento" = true, "tipoEquipamento" = 'Bisturi Elétrico', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Bisturi Elétrico – Por Cirurgia', 'Bisturi Elétrico') ORDER BY ("nome" = 'Bisturi Elétrico – Por Cirurgia') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Bisturi Elétrico – Por Cirurgia', 'Bisturi Elétrico', 'SAUDE'::"CategoriaServico", 'Valor por cirurgia. Profissional Hemoderi entrega, testa e acompanha a cirurgia; inclusas as pontas do kit odontológico da EMAI.', 60, 50000, true, 'Bisturi Elétrico', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Bisturi Elétrico – Por Cirurgia', 'Bisturi Elétrico'));

-- Bisturi Elétrico · Bisturi Elétrico – Diária (8 Horas)
UPDATE "Servico" SET "nome" = 'Bisturi Elétrico – Diária (8 Horas)', "familia" = 'Bisturi Elétrico', "categoria" = 'SAUDE'::"CategoriaServico", "descricao" = 'Valor para diária de até 8 horas, horários flexíveis. Profissional Hemoderi entrega, testa e retira ao final do dia.', "duracaoMin" = 480, "valorPadraoCentavos" = 75000, "exigeEquipamento" = true, "tipoEquipamento" = 'Bisturi Elétrico', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Bisturi Elétrico – Diária (8 Horas)') ORDER BY ("nome" = 'Bisturi Elétrico – Diária (8 Horas)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Bisturi Elétrico – Diária (8 Horas)', 'Bisturi Elétrico', 'SAUDE'::"CategoriaServico", 'Valor para diária de até 8 horas, horários flexíveis. Profissional Hemoderi entrega, testa e retira ao final do dia.', 480, 75000, true, 'Bisturi Elétrico', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Bisturi Elétrico – Diária (8 Horas)'));

-- Motor de Implante · Motor de Implante – Por Cirurgia
UPDATE "Servico" SET "nome" = 'Motor de Implante – Por Cirurgia', "familia" = 'Motor de Implante', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Valor por cirurgia. Profissional Hemoderi entrega, testa e acompanha a cirurgia. Não inclui contra-ângulo e peça reta.', "duracaoMin" = 90, "valorPadraoCentavos" = 50000, "exigeEquipamento" = true, "tipoEquipamento" = 'Motor de Implante', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Motor de Implante – Por Cirurgia', 'Motor de Implante') ORDER BY ("nome" = 'Motor de Implante – Por Cirurgia') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Motor de Implante – Por Cirurgia', 'Motor de Implante', 'ODONTOLOGIA'::"CategoriaServico", 'Valor por cirurgia. Profissional Hemoderi entrega, testa e acompanha a cirurgia. Não inclui contra-ângulo e peça reta.', 90, 50000, true, 'Motor de Implante', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Motor de Implante – Por Cirurgia', 'Motor de Implante'));

-- Motor de Implante · Motor de Implante – Diária (8 Horas)
UPDATE "Servico" SET "nome" = 'Motor de Implante – Diária (8 Horas)', "familia" = 'Motor de Implante', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Valor para diária de até 8 horas, horários flexíveis. Profissional Hemoderi entrega, testa e retira ao final do dia.', "duracaoMin" = 480, "valorPadraoCentavos" = 75000, "exigeEquipamento" = true, "tipoEquipamento" = 'Motor de Implante', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Motor de Implante – Diária (8 Horas)') ORDER BY ("nome" = 'Motor de Implante – Diária (8 Horas)') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Motor de Implante – Diária (8 Horas)', 'Motor de Implante', 'ODONTOLOGIA'::"CategoriaServico", 'Valor para diária de até 8 horas, horários flexíveis. Profissional Hemoderi entrega, testa e retira ao final do dia.', 480, 75000, true, 'Motor de Implante', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Motor de Implante – Diária (8 Horas)'));

-- PRF – Coleta e Produção · Membranas – PRF
UPDATE "Servico" SET "nome" = 'Membranas – PRF', "familia" = 'PRF – Coleta e Produção', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Produção de membranas (A-PRF, A-PRF+, Supermembrana e FLA), com aferição dos sinais vitais e coleta antes do início do procedimento. Sem PRF em fase líquida, sem Stickybone e sem acompanhamento do procedimento. Disponível nas regiões metropolitanas de São Paulo, Rio de Janeiro, Curitiba e Vila Velha.', "duracaoMin" = 30, "valorPadraoCentavos" = 35000, "exigeEquipamento" = true, "tipoEquipamento" = 'Centrífuga PRF', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY['AC','AL','AP','AM','BA','CE','DF','GO','MA','MT','MS','MG','PA','PB','PE','PI','RN','RS','RO','RR','SC','SE','TO']::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Membranas – PRF') ORDER BY ("nome" = 'Membranas – PRF') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Membranas – PRF', 'PRF – Coleta e Produção', 'ODONTOLOGIA'::"CategoriaServico", 'Produção de membranas (A-PRF, A-PRF+, Supermembrana e FLA), com aferição dos sinais vitais e coleta antes do início do procedimento. Sem PRF em fase líquida, sem Stickybone e sem acompanhamento do procedimento. Disponível nas regiões metropolitanas de São Paulo, Rio de Janeiro, Curitiba e Vila Velha.', 30, 35000, true, 'Centrífuga PRF', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY['AC','AL','AP','AM','BA','CE','DF','GO','MA','MT','MS','MG','PA','PB','PE','PI','RN','RS','RO','RR','SC','SE','TO']::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Membranas – PRF'));

-- PRF – Coleta e Produção · Stickybone + Membranas
UPDATE "Servico" SET "nome" = 'Stickybone + Membranas', "familia" = 'PRF – Coleta e Produção', "categoria" = 'ODONTOLOGIA'::"CategoriaServico", "descricao" = 'Produção de membranas (A-PRF, A-PRF+, Supermembrana e FLA), PRF em fase líquida e Stickybone personalizado (enxerto ósseo). Aferição dos sinais vitais e acompanhamento do início ao fim, com coleta e produção durante todo o procedimento. Não fornecemos biomaterial.', "duracaoMin" = 45, "valorPadraoCentavos" = 60000, "exigeEquipamento" = true, "tipoEquipamento" = 'Centrífuga PRF', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('Stickybone + Membranas', 'Stickybone / PRF Block') ORDER BY ("nome" = 'Stickybone + Membranas') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'Stickybone + Membranas', 'PRF – Coleta e Produção', 'ODONTOLOGIA'::"CategoriaServico", 'Produção de membranas (A-PRF, A-PRF+, Supermembrana e FLA), PRF em fase líquida e Stickybone personalizado (enxerto ósseo). Aferição dos sinais vitais e acompanhamento do início ao fim, com coleta e produção durante todo o procedimento. Não fornecemos biomaterial.', 45, 60000, true, 'Centrífuga PRF', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('Stickybone + Membranas', 'Stickybone / PRF Block'));

-- PRF – Coleta e Produção · PRF para Harmonização
UPDATE "Servico" SET "nome" = 'PRF para Harmonização', "familia" = 'PRF – Coleta e Produção', "categoria" = 'ESTETICA'::"CategoriaServico", "descricao" = 'Produção de I-PRF, I-PRF+, S-PRF ou PRP, por paciente/procedimento (sem aplicação). Produção de plasma gel + locação de equipamento: R$ 250,00. Produto disponível dentro da Grande São Paulo.', "duracaoMin" = 45, "valorPadraoCentavos" = 35000, "exigeEquipamento" = true, "tipoEquipamento" = 'Centrífuga PRF', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SE','TO']::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('PRF para Harmonização') ORDER BY ("nome" = 'PRF para Harmonização') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'PRF para Harmonização', 'PRF – Coleta e Produção', 'ESTETICA'::"CategoriaServico", 'Produção de I-PRF, I-PRF+, S-PRF ou PRP, por paciente/procedimento (sem aplicação). Produção de plasma gel + locação de equipamento: R$ 250,00. Produto disponível dentro da Grande São Paulo.', 45, 35000, true, 'Centrífuga PRF', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SE','TO']::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('PRF para Harmonização'));

-- PRF – Coleta e Produção · PRF para Medicina
UPDATE "Servico" SET "nome" = 'PRF para Medicina', "familia" = 'PRF – Coleta e Produção', "categoria" = 'SAUDE'::"CategoriaServico", "descricao" = 'Produção de membranas, PRP, PRF em fase líquida e manipulação de PRF Block. Atuação em consultórios e hospitais.', "duracaoMin" = 45, "valorPadraoCentavos" = 70000, "exigeEquipamento" = true, "tipoEquipamento" = 'Centrífuga PRF', "unidadeCobranca" = 'PACIENTE'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY[]::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('PRF para Medicina') ORDER BY ("nome" = 'PRF para Medicina') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'PRF para Medicina', 'PRF – Coleta e Produção', 'SAUDE'::"CategoriaServico", 'Produção de membranas, PRP, PRF em fase líquida e manipulação de PRF Block. Atuação em consultórios e hospitais.', 45, 70000, true, 'Centrífuga PRF', 'PACIENTE'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY[]::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('PRF para Medicina'));

-- PRF – Coleta e Produção · I-PRF Day
UPDATE "Servico" SET "nome" = 'I-PRF Day', "familia" = 'PRF – Coleta e Produção', "categoria" = 'SAUDE'::"CategoriaServico", "descricao" = 'Produção de I-PRF, I-PRF+, S-PRF ou PRP por 4 horas, até 6 pessoas (sem aplicação). Produção de plasma gel + locação de equipamento: R$ 250,00. Valor para um raio de 150 km da cidade de São Paulo.', "duracaoMin" = 240, "valorPadraoCentavos" = 75000, "exigeEquipamento" = true, "tipoEquipamento" = 'Centrífuga PRF', "unidadeCobranca" = 'PERIODO'::"UnidadeCobranca", "permiteQuantidade" = false, "rotuloQuantidade" = NULL, "quantidadeMinima" = 1, "quantidadeIncluida" = NULL, "valorAdicionalCentavos" = 0, "ufsIndisponiveis" = ARRAY['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SE','TO']::text[], "ativo" = true, "desativadoEm" = NULL, "atualizadoEm" = NOW()
 WHERE "id" = (SELECT "id" FROM "Servico" WHERE "nome" IN ('I-PRF Day') ORDER BY ("nome" = 'I-PRF Day') DESC, "criadoEm" LIMIT 1);
INSERT INTO "Servico" ("id", "nome", "familia", "categoria", "descricao", "duracaoMin", "valorPadraoCentavos", "exigeEquipamento", "tipoEquipamento", "unidadeCobranca", "permiteQuantidade", "rotuloQuantidade", "quantidadeMinima", "quantidadeIncluida", "valorAdicionalCentavos", "ufsIndisponiveis", "ativo", "criadoEm", "atualizadoEm")
SELECT gen_random_uuid()::text, 'I-PRF Day', 'PRF – Coleta e Produção', 'SAUDE'::"CategoriaServico", 'Produção de I-PRF, I-PRF+, S-PRF ou PRP por 4 horas, até 6 pessoas (sem aplicação). Produção de plasma gel + locação de equipamento: R$ 250,00. Valor para um raio de 150 km da cidade de São Paulo.', 240, 75000, true, 'Centrífuga PRF', 'PERIODO'::"UnidadeCobranca", false, NULL, 1, NULL, 0, ARRAY['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SE','TO']::text[], true, NOW(), NOW()
 WHERE NOT EXISTS (SELECT 1 FROM "Servico" WHERE "nome" IN ('I-PRF Day'));

-- Saiu do catálogo atual (desativado, nunca apagado: pedidos antigos apontam para ele).
UPDATE "Servico" SET "ativo" = false, "desativadoEm" = NOW(), "atualizadoEm" = NOW() WHERE "nome" = 'PRF – Coleta e Produção de Concentrados Plaquetários' AND "ativo";

COMMIT;
